# Generated by Django 5.2.7 on 2026-01-12 22:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
    ]
