# Generated by Django 5.2.7 on 2026-01-14 19:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
