# Generated by Django 5.2.7 on 2026-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_debt_created_transaction_debt_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
