# Generated by Django 5.2.7 on 2026-01-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_debt_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Debts'},
        ),
        migrations.AlterField(
            model_name='debt',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='transaction.transaction'),
        ),
    ]
