# Generated by Django 5.2.7 on 2026-05-06 08:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_debt_options_alter_debt_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(unique=True)),
                ('cash_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ebt_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('card_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('debt_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Close',
                'verbose_name_plural': 'Day Closes',
                'ordering': ['-close_date'],
            },
        ),
    ]
