# Generated by Django 5.2.7 on 2026-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_taxable_alter_deposit_deposit_value_and_more'),
    ]

    operations = [
    ]
