# Generated by Django 5.2.7 on 2026-01-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20260114_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='deposit_category',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(
                to='inventory.supplier',
                on_delete=django.db.models.deletion.RESTRICT,
                null=False,  # temporarily allow null for existing rows
                blank=False,
            ),
        ),
        migrations.DeleteModel(
            name='deposit',
        ),
    ]
