# Generated by Django 5.2.7 on 2026-01-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_is_taxable_alter_product_tax_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units removed from stock')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'adjustment_type', 'created_at'], name='inventory_s_product_d069a1_idx')],
            },
        ),
    ]
