# Generated by Django 5.2.7 on 2026-01-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_displayed_items_display_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displayed_items',
            options={'verbose_name_plural': 'Displayed Items'},
        ),
        migrations.AlterField(
            model_name='displayed_items',
            name='variable_price',
            field=models.BooleanField(default=False),
        ),
    ]
