# Generated by Django 5.2.7 on 2026-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_displayed_items_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayed_items',
            name='barcode',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
